language: java
jdk:
- openjdk11
env:
  global:
  - CC_TEST_REPORTER_ID=fc047cea122b36ad172d388e9ebe038eda328ae1aec4931139b7f8e1aff22b4f
  - secure: qw+/+mn0AlQ12nweAhEVbbWrO80PhOlK/mlhMzSEhrrDfCaDstZkaojPR4qgaSbvCXlJItQfV+SqeWle10rQ0Xn+2VeO/Ao3H6X4Z3VOTK2Fuf6ISfJQKPa/rnIMM2n90qdVNJcXUWqVaMicSAmQ1JlK1QAvPo8Z2zLfsURq8vc0QjoAOtgPUAXCeVsObtiTChnfHyYQgLUZTbiu78XsL1giM6Y9oawoUl2U+X6iAiwmZaRHJuuAQ4sbBnko8Jd68ai/ildurAr3PB2DkeQMn422XDf9s0CO+erk4uWZGsneKgcUJI8ZPOCe2D7LOEHEasqxFlo5iqy2aKmFW2MvmFHuH6nOLZxtRvKJ+Y4gY6ElnrSF/gLVmPwRo5k6ib0J0QnGlL9Cvx5SW/w4LtIpeEt+SaM4qoa4wFFwIIUnA/OTDLng4/K5zb+pdmRuu0trQN3Vy7aw3Q2Rqfv12E49bptXUHqwcXmw+JSzUwsIl+NM/WGMhsKvykar0UbUpGpOiC2CawNSFCrud2KhltdXzbjQpOWCPSl3NguFenQ/kbX65EOZLOJaPPmtPbEfyV/ciZS8dp8C5wFLht5jybxW3VPFbNRhDJW1hmWAZWkzy4Lg2qzrK1Tqg6pwYYEq9uEqmEjLfkVtbO4ms69Z1if0D0lreaB0fqvGVdfuKdLQ1fc=
  - secure: YRR1zyE9E7n7XR8YQvvhYRvCBQ9IKh25h4zBFThgXIkEaT4s0Umeh9FqUSq5v/v7xkX5FvdRq6/mDfbEDAC1+tsfke1jM4bTUA8sQNkqZlojBz/Ql2oo0mxQsPdTnXx1jSAyC9yDeg9MGiQjv8icgf1d4ETbWJIlkR9JykjwexbXQyKPNC4S6ePweb0AEe+h0HOKpE8g4B8AfXgiJlMRIOxbkv3B+f6bBeI1G0z/ue9odN573VBJeG4J1fZnJCvkucm/Q5y2aifDpSKL9MlQ2lTMOv3RUJeORJSYmux8+ldEorENIoeBpgHlR4RAwk0xj86sQEOORGKfn4qLez96Vm8tWn2iud7l4ff/pFK2jX60J8pHEfzR2Jflt36f3P8F5ggYCnQytXsXpyQJNX7w/jxJdmCfPLuK3k3g864KhN2PuTqrVgmifAWxw8BZFpv+555o4y5YSuzlqMUZoP9V3yOkUV7hb8knytuZ4rJUMpNFOkphP1k/gBJffGabk2CTzZ2FNowpY1mqfUbSzuyo/POya/hngW0mMOmn8U8UCruYhOMjQJ+we8fut77OgCjQ7XpjlTaL7f1oWyMIaRea2YGTHJ1SfyCSYbJeEVWGEIk0DxwP6/AmLVjYxeTXjxnb/0SJzTMAidzQaiJVWZVrj1BMGZQ9FEB4EwkaT68pQDI=
  - secure: QwT018fSSo5ZhDpSsLbdL9LVkyY6s5JzYC8iXmMYpLC7YDSWCxL11A/Dyi1d+9ltSCg7qet/PRpP2OLwrVzMfisg/+rCAPi5rFXnGmjJCLB6CtcfGaHLA88agKj96YuFGJXuNsykDA/N7iIwzRCOvDDMqNTL70WQsCgk0iilErEqOKZ/rLeXonKlCsOb5eRf/BLujfX3fBG07QxAvt2YlNk8zQaqtc2AwQTByt/Im3/k4ANEXQHbgubSsSWKp/cI1/17RRJMaTUSHslgTT0uCsctKE0xoaS/4lBRPDH+w2MnxD/wIb1mY56jXwZUImCKcKseM4JL5d92b6YNEgFNdh7c4Qfc3F9Z20jkYah20OFo5oPUG6zsNZz2dqC+jMheuEwrmX8Bmg8pcnnFDXw8W9aHCreJQF2kc9FkC4sQhDH66qvoT0/5hrO5SfG24WdmjQjw3Pssq/tgMD9g4hbwxza9Gn77fqwJJeqsLGeA8g9hC8iStxA1yvXFCH0wx0mk5dlkJ3wPrMPRYebO13yAEbt9GL8eLZqqHCwNYCTO2t4B02ntVJFPNSDfMpjYDoKlfGe0oK3P/nwfiGllR3CyvHkGcCeztckNtI/mU2tm7VsivfwTDHUKc6wJUpqqZ2lmz59NRnuNWEMvYWWC2bzumS6vmmcHmkMfGPu6pxStTS8=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/jackson-module-http-query
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: YGcXyBpVTfC1sH+/zXcOggnHZiszaWjJFUYSDbzXWyvEzTyvXkfns/Ym/9uhb4fLaYv03vdzzQuePCMHOkfoiYtYldEN+YxIqObdS+W29JuBhHJpM9Uw+Ncg7FjyBlJqiDOE2p6EaPwtZTqw9Qv7eJdOR7mLFK4myAaDdRR2ydUoQxPls9D5tyJHb7H6dY3GiCwPtKyU+kcgnDB+6zGAFKFwfkzML/o4X4TWQeszWU9q6BXRsMTBzRfs+aW5hDWafvakz4S6PcoZc/4WWKXAcG1KBQjoBxjPzUxmnXcGyNMPJdLyY0BcAaiaE8VS9oXSlMOY/8ifIHQ8kmfqmmZFJ8slgV7ob/DE0QT6lE1FoQETYEjsyuUJxWZ3kzRqfIcGiKbTE0bwhk+ygIyd2l8tZapSMXOCSRzaHFpDDengFfdvtRV33oKi+/HFdmR2j/bCjlPyw4qgRch7IY8PVAgL98iqsI1TCKXCFjoTifvGL7G703NzJlKTsrR2snSSgXJvSmJmvQoOjD2OU8gWlq++1hjAhKiUC96+TLneAQvZ2DNnSOrQhioyh7MHFXz8v98uah4bsG3IiHQ+GNwQKBecNvns0tSUMqfyKiHarF0GtdmxNgvmzKEt3jC0WNeILnCG1jMN9hZRkX/uoBS9h5X+f48S7coUGdQEMxVMDziUEHY=
  file: "./target/jackson-module-http-query-$project_version.jar"
  on:
    repo: trickl/jackson-module-http-query
